### ISSUE TITLE
📝 Make awesome clean architecture repo public & friendly

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/awesome-clean-architecture#5]
For the awesome-clean-architecture repo (https://github.com/SSWConsulting/awesome-clean-architecture), add the following:

- [x] Branch protection
- [ ] Code Scanning
- [x] CODEWONERS
- [x] LICENSE
- [x] README
- [ ] Issue Template Forms

**Comment by Hona** [comment]
Mostly Done - Not doing code scanning or issue templates.

Maybe revisit issue templates later
